### ISSUE TITLE
EmptyPage: That page number is less than 1

### ISSUE THREAD

**Issue by mhib** [iiuni/projektzapisy#241]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/87/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/87/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1505755678/zapisy/apps/users/decorators.py", line 76, in __call__
    return self.view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1505755678/zapisy/apps/grade/poll/views.py", line 541, in polls_list
    "return render_to_response( 'grade/poll/managmen...a, context_instance = RequestContext( request ))"
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/shortcuts.py", line 25, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader.py", line 178, in render_to_string
    return t.render(context_instance)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 898, in render
    output = self.filter_expression.resolve(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 596, in resolve
    obj = self.var.resolve(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 734, in resolve
    value = self._resolve_lookup(context)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/template/base.py", line 788, in _resolve_lookup
    current = current()
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/paginator.py", line 141, in previous_page_number
    return s

**Comment by jasiekmarc** [comment]
Od roku nie występuje. Zamykam.
