### ISSUE TITLE
DoesNotExist: UserProfile matching query does not exist.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#255]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/103/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/103/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1508968754/zapisy/apps/users/views.py", line 172, in set_language
    account = UserProfile.objects.get(user=request.user)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: UserProfile matching query does not exist.
```

**Comment by jasiekmarc** [comment]
Zamknięte, bo `AbstractUser` ani `UserProfile` już nie istnieje.
