### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one SingleChoiceQuestionAnswer -- it returned 2!

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#343]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/120/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/120/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1516817829/zapisy/apps/grade/poll/views.py", line 1215, in poll_results_detailed
    form.setFields( poll, st )
  File "/home/zapisy/projektzapisy/releases/1516817829/zapisy/apps/grade/poll/forms.py", line 140, in setFields
    question     = question ).option.pk
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one SingleChoiceQuestionAnswer -- it returned 2!
```

**Comment by jasiekmarc** [comment]
Zdarzyło się raz, rok temu.
