### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#362]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/131/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/131/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1517614212/zapisy/apps/grade/poll/views.py", line 972, in poll_answer
    "return HttpResponseRedirect( '/grade/poll/poll_... data['prev'][3]) + '/' + str( data['prev'][0]))"
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by jasiekmarc** [comment]
Raz, rok temu.
