### ISSUE TITLE
DisallowedRedirect: Unsafe redirect to URL with protocol 'android-app'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#366]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/134/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/134/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django_cas_ng/views.py", line 95, in login
    return HttpResponseRedirect(next_page)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/http/response.py", line 431, in __init__
    raise DisallowedRedirect("Unsafe redirect to URL with protocol '%s'" % parsed.scheme)
DisallowedRedirect: Unsafe redirect to URL with protocol 'android-app'
```

**Comment by jasiekmarc** [comment]
To zdarzyło się raz i raczej nie jest winą Systemu Zapisów.
