### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#382]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/149/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/149/)

```
Traceback (most recent call last):
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 503, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env27/local/lib/python2.7/site-packages/django/views/generic/list.py", line 160, in get
    self.object_list = self.get_queryset()
  File "/home/zapisy/projektzapisy/releases/1519519189/zapisy/apps/schedule/views.py", line 323, in get_queryset
    groups = Group.objects.filter(reduce(operator.or_, query))
TypeError: reduce() of empty sequence with no initial value
```

**Comment by jasiekmarc** [comment]
Raz, rok temu.
