### ISSUE TITLE
ValueError: year 21082 is out of range

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#464]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/185/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/185/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1527223015/zapisy/apps/schedule/views.py", line 280, in ajax_get_terms
    time = datetime.date(int(year), int(month), int(day))
ValueError: year 21082 is out of range
```

**Comment by jasiekmarc** [comment]
Błąd interfejsu rezerwacji sali.

**Comment by jasiekmarc** [comment]
Zamykamy w związku z #895.
