### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.date'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#484]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/194/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/194/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1528592178/zapisy/apps/schedule/views.py", line 266, in ajax_get_terms
    terms = Classroom.get_terms_in_day(time, ajax=True)
  File "/home/zapisy/projektzapisy/releases/1528592178/zapisy/apps/enrollment/courses/models/classroom.py", line 116, in get_terms_in_day
    if selected_semester.lectures_beginning > date or date > selected_semester.lectures_ending:
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.date'
```

**Comment by lewymati** [comment]
Problem występuje gdy nowo utworzony semestr nie ma wpisanych dat początku lub końca zajęć. Czasem uniemożliwia to rezerwowanie sal, gdy data rezerwacji wybiega daleko w przyszłość, np. na następny semestr.
