### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#613]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/228/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/228/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/projektzapisy/releases/1548970270/zapisy/apps/grade/poll/views.py", line 1046, in poll_answer
    str(data['next'][3]) + '/' + str(data['next'][0]))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by jasiekmarc** [comment]
Zamykam w związku z powstaniem nowej oceny zajęć #689.
