### ISSUE TITLE
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#618]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/229/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/229/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/projektzapisy/releases/1549997903/zapisy/apps/enrollment/courses/views.py", line 146, in course_view
    course, data = course_view_data(request, slug)
  File "/home/zapisy/projektzapisy/releases/1549997903/zapisy/apps/enrollment/courses/views.py", line 103, in course_view_data
    student_can_enqueue = Record.can_enqueue_groups(student, course.groups.all())
  File "/home/zapisy/projektzapisy/releases/1549997903/zapisy/apps/enrollment/records/models/records.py", line 113, in can_enqueue_groups
    ret = GroupOpeningTimes.are_groups_open_for_student(student, groups, time)
  File "/home/zapisy/projektzapisy/releases/1549997903/zapisy/apps/enrollment/records/models/opening_times.py", line 160, in are_groups_open_for_student
    is_after_t0 = T0Times.is_after_t0(student, groups[0].course.semester, time)
  File "/home/zapisy/projektzapisy/releases/1549997903/zapisy/apps/enrollment/records/models/opening_times.py", line 46, in is_after_t0
    if time > semester.records_closing:
TypeError: '>' not supported between instances of 'datetime.datetime' and 'NoneType'
```

**Comment by jasiekmarc** [comment]
@lewymati Czy `semester.records_closing` nie powinno być ustalone?
