### ISSUE TITLE
DoesNotExist: Semester matching query does not exist.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#637]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/238/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/238/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1550270223/zapisy/apps/grade/ticket_create/views.py", line 80, in connections_choice
    students_polls = Poll.get_all_polls_for_student(request.user.student)
  File "/home/zapisy/projektzapisy/releases/1550270223/zapisy/apps/grade/poll/models/poll.py", line 254, in get_all_polls_for_student
    student=student) if not x.group or x.group.id in groups]
  File "/home/zapisy/projektzapisy/releases/1550270223/zapisy/apps/grade/poll/models/poll.py", line 181, in get_current_polls
    semester = Semester.objects.get(is_grade_active=True)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
DoesNotExist: Semester matching query does not exist.
```

**Comment by jasiekmarc** [comment]
Ostatnio wystąpiło ponad 100 dni temu. Zamykam.
