### ISSUE TITLE
SMTPSenderRefused: (421, b'4.7.0 Try again later, closing connection. (MAIL) u12sm5898650wmf.44 - gsmtp', 'zapisy@cs.uni.wroc.pl')

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#640]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/242/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/242/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1550270223/zapisy/apps/email_change/views.py", line 96, in email_change_view
    send_mail('[Fereol] Weryfikacja zmiany adresu email', message, None, [email])
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/__init__.py", line 60, in send_mail
    return mail.send()
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/message.py", line 294, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
    sent = self._send(message)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 126, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.6/smtplib.py", line 867, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
SMTPSenderRefused: (421, b'4.7.0 Try again later, closing connection. (MAIL) u12sm5898650wmf.44 - gsmtp', 'zapisy@cs.uni.wroc.pl')
```

**Comment by jasiekmarc** [comment]
@lewymati: Czy maile się tej nocy wysłały?

**Comment by lewymati** [comment]
Kurczę, faktycznie. Chyba znów przekroczyliśmy jakieś limity.
