### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'user'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#649]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/245/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/245/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1551735841/zapisy/apps/enrollment/courses/views.py", line 194, in group_view
    request.user, group),
  File "/home/zapisy/projektzapisy/releases/1551735841/zapisy/apps/enrollment/courses/views.py", line 161, in can_user_view_students_list_for_group
    is_user_group_teacher = user == group.teacher.user
AttributeError: 'NoneType' object has no attribute 'user'
```

**Comment by jasiekmarc** [comment]
Jak napisałem w #982, warto się zastanowić, czy pole `teacher` w modelu `Group` nie powinno po prostu być `NOT NULL`. Trzeba przyjrzeć się, czy nie spowoduje to błędów przy importowaniu planu zajęć.
