### ISSUE TITLE
TypeError: '>' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#652]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/246/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/246/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1551735841/zapisy/apps/grade/poll/views.py", line 297, in poll_form
    data = prepare_data_for_create_poll(request, group_id)
  File "/home/zapisy/projektzapisy/releases/1551735841/zapisy/apps/grade/poll/utils.py", line 727, in prepare_data_for_create_poll
    if group_id > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by jasiekmarc** [comment]
Do naprawienia przy okazji przepisywania aplikacji Poll.
