### ISSUE TITLE
ParseError: not well-formed (invalid token): line 119, column 212

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#656]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/247/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/247/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 81, in login
    request=request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/backends.py", line 22, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 165, in verify_ticket
    return self.verify_response(response)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 258, in verify_response
    return cls.parse_response_xml(response)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 222, in parse_response_xml
    tree = ElementTree.fromstring(response)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
ParseError: not well-formed (invalid token): line 119, column 212
```

**Comment by jasiekmarc** [comment]
Eksperymenty @lewymati
