### ISSUE TITLE
ProgrammingError: relation "proposal_proposal" does not exist
LINE 1: ...mation_ptr_id", "proposal_proposal"."status" FROM "proposal_...
                                                             ^


### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#665]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/248/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/248/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1554312813/zapisy/apps/offer/proposal/views.py", line 214, in proposal_edit
    proposal = Proposal.objects.get(slug=slug)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
ProgrammingError: relation "proposal_proposal" does not exist
LINE 1: ...mation_ptr_id", "proposal_proposal"."status" FROM "proposal_...
                                                             ^
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
ProgrammingError: relation "proposal_proposal" does not exist
LINE 1: ...mation_ptr_id", "proposal_proposal"."status" FROM "proposal_...
                                                             ^

```

**Comment by jasiekmarc** [comment]
Specjalnie wywołane na stagingu.
