### ISSUE TITLE
ValueError: time data '1528095600' does not match format '%Y-%m-%d'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#675]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/254/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/254/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/home/zapisy/projektzapisy/releases/1556207643/zapisy/apps/schedule/views.py", line 279, in get_queryset
    queryset = super(ClassroomTermsAjaxView, self).get_queryset()
  File "/home/zapisy/projektzapisy/releases/1556207643/zapisy/apps/utils/fullcalendar.py", line 198, in get_queryset
    start = datetime.datetime.strptime(start, "%Y-%m-%d")
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '1528095600' does not match format '%Y-%m-%d'
```

**Comment by jasiekmarc** [comment]
To jest kurcze bardzo dziwne. Ostatnio wszystkie błędy, które pojawiają się w systemie są generowane przez jakieś _Googleboty_ i _Bingboty_. Co one robią? Wpisują losowe URL-e?
