### ISSUE TITLE
TemplateDoesNotExist: offer/proposal/summary_table.html

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#676]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/255/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/255/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1556541473/zapisy/apps/offer/vote/views.py", line 110, in vote_summary
    return render(request, 'offer/vote/summary.html', data)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
TemplateDoesNotExist: offer/proposal/summary_table.htmlTraceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 176, in render
    template = context.template.engine.get_template(template_name)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/engine.py", line 130, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
TemplateDoesNotExist: offer/proposal/summary_table.html
```

**Comment by jasiekmarc** [comment]
Naprawiam to przy okazji przepisywania aplikacji `vote`.

**Comment by jasiekmarc** [comment]
Fixed in #678.
