### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#684]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/260/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/260/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1556541473/zapisy/apps/enrollment/timetable/views.py", line 126, in my_timetable
    return render(request, 'timetable/timetable.html', data)
UnboundLocalError: local variable 'data' referenced before assignment
```

**Comment by jasiekmarc** [comment]
Do szybkiego naprawienia. Okazuje się, że są użytkownicy, którzy nie są ani studentami ani pracownikami. W tym miejscu
https://github.com/iiuni/projektzapisy/blob/4ac0296ee3419c8dd8f9733c3b4efa2cc4ad2039/zapisy/apps/enrollment/timetable/views.py#L126
trzeba im wyświetlić warning (za pomocą djangowych _messages_) i przekierować na stronę główną.
