### ISSUE TITLE
ParseError: undefined entity &copy;: line 44, column 37

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#690]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/261/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/261/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 39, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 91, in get
    request=request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/backends.py", line 21, in authenticate
    username, attributes, pgtiou = client.verify_ticket(ticket)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 165, in verify_ticket
    return self.verify_response(response)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 206, in verify_response
    user, attributes, pgtiou = cls.parse_response_xml(response)
  File "/home/zapisy/env36/lib/python3.6/site-packages/cas.py", line 222, in parse_response_xml
    tree = ElementTree.fromstring(response)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
ParseError: undefined entity &copy;: line 44, column 37
```

**Comment by jasiekmarc** [comment]
Jakieś historie z CAS. Nie jest to błąd w Systemie Zapisów.
