### ISSUE TITLE
AttributeError: type object 'CourseEntity' has no attribute 'statistics'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#698]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/267/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/267/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1559570548/zapisy/apps/statistics/views.py", line 50, in votes
    proposals = CourseEntity.statistics.in_year()
AttributeError: type object 'CourseEntity' has no attribute 'statistics'
```

**Comment by jasiekmarc** [comment]
Closed by https://github.com/iiuni/projektzapisy/commit/444bcc65896331029f874ceadd1ca488c435d86a
