### ISSUE TITLE
AttributeError: 'CASClientV2' object has no attribute 'get_saml_slos'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#700]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/268/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/268/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 39, in dispatch
    return super(LoginView, self).dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 58, in post
    clean_sessions(client, request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 200, in clean_sessions
    for slo in client.get_saml_slos(request.POST.get('logoutRequest')):
AttributeError: 'CASClientV2' object has no attribute 'get_saml_slos'
```

**Comment by jasiekmarc** [comment]
Bug w paczce _django_cas_ng_. Naprawiony _upstream_ (https://github.com/mingchen/django-cas-ng/commit/88f65251a5e060c27123a24beb60f9856e94f4c6).
