### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one SingleChoiceQuestionAnswer -- it returned 2!

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#708]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/270/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/270/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/projektzapisy/releases/1559597669/zapisy/apps/grade/poll/views.py", line 1031, in poll_answer
    form.setFields(poll, st)
  File "/home/zapisy/projektzapisy/releases/1559597669/zapisy/apps/grade/poll/forms.py", line 139, in setFields
    question=question).option.pk
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one SingleChoiceQuestionAnswer -- it returned 2!
```

**Comment by jasiekmarc** [comment]
Do zamknięcia w związku z #689.
