### ISSUE TITLE
SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor n18sm8811765wru.2 - gsmtp')

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#727]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/273/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/273/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/views.py", line 220, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/views.py", line 233, in form_valid
    form.save(**opts)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 295, in save
    email, html_email_template_name=html_email_template_name,
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 250, in send_mail
    email_message.send()
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 110, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. Learn more at\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor n18sm8811765wru.2 - gsmtp')
```

**Comment by jasiekmarc** [comment]
Problem rozwiązany przez @mpyzik. Dodano _app password_ dla Systemu Zapisów.
