### ISSUE TITLE
DoesNotExist: CourseInstance matching query does not exist.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#733]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/276/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/276/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1568065422/zapisy/apps/enrollment/timetable/views.py", line 235, in prototype_get_course
    course = CourseInstance.objects.get(pk=course_id)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
DoesNotExist: CourseInstance matching query does not exist.
```

**Comment by jasiekmarc** [comment]
Ten kurs chyba po prostu został w międzyczasie usunięty. Nie wydaje mi się, żeby zdarzyło się coś niepokojącego.
