### ISSUE TITLE
TemplateDoesNotExist: registration/login.html

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#747]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/278/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/278/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
TemplateDoesNotExist: registration/login.html
```

**Comment by jasiekmarc** [comment]
Do zamknięcia w związku z #875.
