### ISSUE TITLE
DoesNotExist: Semester matching query does not exist.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#815]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/285/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/285/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/projektzapisy/releases/1573064018/zapisy/apps/enrollment/courses/views.py", line 45, in courses_list
    semester = Semester.objects.get(pk=semester_id)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
DoesNotExist: Semester matching query does not exist.
```

**Comment by jasiekmarc** [comment]
Faktycznie taki semestr nie istnieje. Ktoś próbował być zbyt mądry.
