### ISSUE TITLE
AttributeError: 'Template' object has no attribute 'course'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#821]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/286/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/286/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/api/function_trace.py", line 98, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 706, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 291, in lookup_field
    value = attr()
  File "/home/zapisy/projektzapisy/releases/1573064018/zapisy/apps/grade/poll/models/template.py", line 50, in __str__
    if self.course:
AttributeError: 'Template' object has no attribute 'course'Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
FieldDoesNotExist: Template has no field named '__str__'Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: '__str__'
```

**Comment by jasiekmarc** [comment]
Błąd jest w tej linijce: https://github.com/iiuni/projektzapisy/blob/9cbcb935fa4d4cf676ee197db903fe7539ae1bae/zapisy/apps/grade/poll/models/template.py#L50.
Nie wiem, czemu się nigdy wcześniej nie ujawnił.
