### ISSUE TITLE
IntegrityError: update or delete on table "courses_courseinformation" violates foreign key constraint "courses_courseinstan_courseinformation_pt_715a9a14_fk_courses_c" on table "courses_courseinstance"
DETAIL:  Key (id)=(2422) is still referenced from tab

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#830]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/289/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/289/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1828, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 71, in commit
    return self.__wrapped__.commit()
IntegrityError: update or delete on table "courses_courseinformation" violates foreign key constraint "courses_courseinstan_courseinformation_pt_715a9a14_fk_courses_c" on table "courses_courseinstance"
DETAIL:  Key (id)=(2422) is still referenced from table "courses_courseinstance".
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 71, in commit
    return self.__wrapped__.commit()
ForeignKeyViolation: update or delete on table "courses_courseinformation" violates foreign key constraint "courses_courseinstan_courseinformation_pt_715a9a14_fk_courses_c" on table "courses_courseinstance"
DETAIL:  Key (id)=(2422) is still referenced from table "courses_courseinstance".

```

**Comment by jasiekmarc** [comment]
@matpyz próbował usunąć propozycję przedmiotu o id=2422. Z jakiegoś powodu obiekt bazowy `CourseInformation` był współdzielony przez tę propozycję oraz obiekt `CourseInstance`. Przypuszczam, że obiekty te zostały niepoprawnie utworzone ręcznie.
