### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#832]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/290/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/290/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1580763700/zapisy/apps/grade/poll/views.py", line 53, in post
    correct_polls, failed_polls = RSAKeys.parse_raw_tickets(tickets)
  File "/home/zapisy/projektzapisy/releases/1580763700/zapisy/apps/grade/ticket_create/models/rsa_keys.py", line 49, in parse_raw_tickets
    tickets_list = tickets['tickets']
TypeError: 'int' object is not subscriptable
```

**Comment by jasiekmarc** [comment]
Ktoś próbuje wkleić same klucze w tablicy.
