### ISSUE TITLE
KeyError: 'signature'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#837]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/293/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/293/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/grade/poll/views.py", line 51, in post
    correct_polls, failed_polls = RSAKeys.parse_raw_tickets(tickets)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/grade/ticket_create/models/rsa_keys.py", line 73, in parse_raw_tickets
    signed_ticket = int(tickets['signature'].encode())
KeyError: 'signature'
```

**Comment by jasiekmarc** [comment]
Fixed in 5e5347e2ca93eda5c07e70252aa706187995df7b
