### ISSUE TITLE
TypeError: unsupported operand type(s) for -=: 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#839]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/294/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/294/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1701, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1400, in response_action
    response = func(self, request, queryset)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/enrollment/courses/admin.py", line 52, in refresh_opening_times
    T0Times.populate_t0(semester)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/enrollment/records/models/opening_times.py", line 89, in populate_t0
    minutes=((student.ects * settings.ECTS_BONUS) // 720) * 720)
TypeError: unsupported operand type(s) for -=: 'NoneType' and 'datetime.timedelta'
```

**Comment by jasiekmarc** [comment]
Administrator próbował policzyć czasy otwarcia zapisów, ale nie ustawił początku zapisów w semestrze.
