### ISSUE TITLE
KeyError: 15909

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#841]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/296/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/296/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/enrollment/timetable/views.py", line 293, in prototype_update_groups
    group_dicts = build_group_list(groups)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/enrollment/timetable/views.py", line 31, in build_group_list
    stats = Record.groups_stats(groups)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/enrollment/records/models/records.py", line 290, in groups_stats
    ret_dict[rec['group_id']]['num_enrolled'] = rec['num_enrolled']
KeyError: 15909
```

**Comment by jasiekmarc** [comment]
Niemal na pewno nastąpił jakiś wyścig (wypisanie z kolejki jednoczesne z updatem). Niegroźne.
