### ISSUE TITLE
DoesNotExist: RSAKeys matching query does not exist.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#842]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/297/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/297/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/grade/poll/views.py", line 51, in post
    correct_polls, failed_polls = RSAKeys.parse_raw_tickets(tickets)
  File "/home/zapisy/projektzapisy/releases/1581090614/zapisy/apps/grade/ticket_create/models/rsa_keys.py", line 71, in parse_raw_tickets
    keys = RSAKeys.objects.get(poll=poll)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
DoesNotExist: RSAKeys matching query does not exist.
```

**Comment by jasiekmarc** [comment]
Ktoś próbował ocenić zajęcia po zamknięciu oceny. System zachował się w zasadzie właściwie.
