### ISSUE TITLE
ValueError: Cannot use None as a query value

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#865]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/310/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/310/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1583579230/zapisy/apps/schedule/views.py", line 63, in reservation
    if formset.is_valid():
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/formsets.py", line 301, in is_valid
    self.errors
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/formsets.py", line 281, in errors
    self.full_clean()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/formsets.py", line 329, in full_clean
    form_errors = form.errors
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/forms.py", line 383, in full_clean
    self._post_clean()
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/forms/models.py", line 403, in _post_clean
    self.instance.full_clean(exclude=exclude, validate_unique=False)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/base.py", line 1137, in full_clean
    self.clean()
  File "/home/zapisy/projektzapisy/releases/1583579230/zapisy/apps/schedule/models/term.py", line 101, in clean
    self.validate_against_course_terms()
  File "/home/zapisy/projektzapisy/releases/1583579230/zapisy/apps/schedule/models/term.py", line 55, in validate_against_course_terms
    semester = Semester.get_semester(self.day)
  File "/home/zapisy/projektzapisy/releases/1583579230/zapisy/apps/enrollment/courses/models/semester.py", line 196, in get_semester
    semester_ending__gte=date)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1101, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

**Comment by jasiekmarc** [comment]
W formularz rezerwacji sali wpisano datę _275760-03-09_, co spowodowało błąd w jakiejś funkcji.

Rozwiązaniem tego (i wielu innych) błędu będzie przepisanie tego formularza z użyciem Django Forms.

**Comment by jasiekmarc** [comment]
Zamykam w związku z #895.
