### ISSUE TITLE
Exception: Non-local url is forbidden to be redirected to.

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#898]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/315/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/315/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 76, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/framework_django.py", line 876, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 107, in get
    next_page = clean_next_page(request, request.GET.get('next'))
  File "/home/zapisy/env36/lib/python3.6/site-packages/django_cas_ng/views.py", line 49, in clean_next_page
    raise Exception("Non-local url is forbidden to be redirected to.")
Exception: Non-local url is forbidden to be redirected to.
```

**Comment by jasiekmarc** [comment]
Błąd pojawił się w wyniku aktualizacji `django-cas-ng` (#880). Nowa wersja dokonuje [sprawdzenia](https://github.com/django-cas-ng/django-cas-ng/blob/a60a72212727def791c3a1273e7490aec80ccf24/django_cas_ng/views.py#L40), którego url "https://zapisy.ii.uni.wroc.pl/" nie przechodzi.

Badam, jak można to naprawić.
