### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "vote_singlevote_proposal_id_state_id_student_id_8b290d81_uniq"
DETAIL:  Key (proposal_id, state_id, student_id)=(719, 17, 2483) already exists.


### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#910]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/322/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/322/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1590766941/zapisy/apps/offer/vote/views.py", line 37, in vote
    formset = prepare_vote_formset(system_state, request.user.student)
  File "/home/zapisy/projektzapisy/releases/1590766941/zapisy/apps/offer/vote/forms.py", line 84, in prepare_vote_formset
    SingleVote.create_missing_votes(student, state)
  File "/home/zapisy/projektzapisy/releases/1590766941/zapisy/apps/offer/vote/models/single_vote.py", line 106, in create_missing_votes
    SingleVote.objects.bulk_create(new_votes)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 493, in bulk_create
    objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts,
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 1223, in _batched_insert
    ignore_conflicts=ignore_conflicts,
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
IntegrityError: duplicate key value violates unique constraint "vote_singlevote_proposal_id_state_id_student_id_8b290d81_uniq"
DETAIL:  Key (proposal_id, state_id, student_id)=(719, 17, 2483) already exists.
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/zapisy/env36/lib/python3.6/site-packages/newrelic-2.68.0.50/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
UniqueViolation: duplicate key value violates unique constraint "vote_singlevote_proposal_id_state_id_student_id_8b290d81_uniq"
DETAIL:  Key (proposal_id, state_id, student_id)=(719, 17, 2483) already exists.

```

**Comment by jasiekmarc** [comment]
Obstawiam, że student miał formularz głosowania otwarty w dwóch oknach przeglądarki i w obu próbował zagłosować. Serwer nie pozwala stworzyć zduplikowanych głosów.

**Comment by jasiekmarc** [comment]
Jest to zaszyte bardzo głęboko w Django, więc nie będziemy tego zmieniać.
