### ISSUE TITLE
AttributeError: 'QuerySet' object has no attribute 'exist'

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#912]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/323/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/323/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1590766941/zapisy/apps/enrollment/courses/views.py", line 201, in group_enrolled_csv
    if not Group.objects.filter(id=group_id).exist():
AttributeError: 'QuerySet' object has no attribute 'exist'
```

**Comment by matpyz** [comment]
Łatka ode mnie w drodze.
