### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#939]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/331/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/331/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1595242019/zapisy/apps/offer/plan/views.py", line 78, in plan_view
    balance = float(employee[11]) if employee[11] else 0
IndexError: list index out of range
```

**Comment by jasiekmarc** [comment]
Zamknięte przez #942.
