### ISSUE TITLE
ImproperlyConfigured: Set the GDRIVE_SERVICE_TYPE environment variable

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#959]
View details in Rollbar: [https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/338/](https://rollbar.com/IIUniversityofWroclaw/System-Zapisow/items/338/)

```
Traceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zapisy/env36/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/zapisy/projektzapisy/releases/1599832120/zapisy/apps/offer/assignments/views.py", line 41, in plan_view
    assignments_spreadsheet = create_sheets_service(CLASS_ASSIGNMENT_SPREADSHEET_ID)
  File "/home/zapisy/projektzapisy/releases/1599832120/zapisy/apps/offer/assignments/sheets.py", line 31, in create_sheets_service
    "type": env('GDRIVE_SERVICE_TYPE'),
  File "/home/zapisy/env36/lib/python3.6/site-packages/environ/environ.py", line 130, in __call__
    return self.get_value(var, cast=cast, default=default, parse_default=parse_default)
  File "/home/zapisy/env36/lib/python3.6/site-packages/environ/environ.py", line 275, in get_value
    raise ImproperlyConfigured(error_msg)
ImproperlyConfigured: Set the GDRIVE_SERVICE_TYPE environment variableTraceback (most recent call last):
  File "/home/zapisy/env36/lib/python3.6/site-packages/environ/environ.py", line 271, in get_value
    value = self.ENVIRON[var]
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'GDRIVE_SERVICE_TYPE'Traceback (most recent call last):
  File "/usr/lib/python3.6/os.py", line 666, in __getitem__
    value = self._data[self.encodekey(key)]
KeyError: b'GDRIVE_SERVICE_TYPE'
```

**Comment by jasiekmarc** [comment]
Naprawione. Dodano zmienną środowiskową.
